name: Bug Report
description: File a bug report.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Please fill out the details below to help us understand and resolve the issue effectively.**
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue or the goal you are trying to achieve with the Ollama Chart.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: chart-version
    attributes:
      label: Chart version
      description: Please provide the version of the Ollama Chart you are using.
      placeholder: 0.x.x
    validations:
      required: true
  - type: input
    id: Kubernetes-version
    attributes:
      label: Kubernetes version
      description: Please specify the version of Kubernetes you are using.
      placeholder: 1.x.x
    validations:
      required: true
  - type: input
    id: Kubernetes-distribution
    attributes:
      label: Kubernetes distribution
      description: Please mention the Kubernetes engine you are using (e.g., k8s, k3s, minikube, kind, rancher).
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If relevant, please provide the logs from the pods to help diagnose the issue. (Enable OLLAMA_DEBUG for more details)
      render: shell
  - type: textarea
    id: values
    attributes:
      label: Your values.yaml
      description: Please share the contents of your values.yaml file. If sensitive information is included, consider redacting it.
      render: yaml
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      render: markdown